# +
# | Author: Markiesch
# | Discord: https://discord.com/invite/jwzrjCkEFG
# | Resource page: https://www.spigotmc.org/resources/epic-replant.95096/
# | Documentation: https://mark-schuurmans.gitbook.io/epic-replant/
# |
# | config generated at version ${project.version}
# +

HelpPage:
  # Disables/enables the help page which is shown when typing /epicreplant
  enabled: true
  # The content of the help page, use [version] to display the plugin version
  content:
    - "&c&lEpicReplant &8>> &7version [version] Created with <3 by &cMarkiesch"
    - ""
    - "&8- &c/epicreplant &7- Shows this help page"
    - "&8- &c/epicreplant reload &7- Reloads the config files."

CropBreak:
  # Disables/enables the whole replant system (a full server restart is needed to apply changes for this option)
  enabled: true
  # When 'true' players need the permission epicreplant.replant to replant crops
  requirePermission: true
  # Use '[]' or '-' to allow replanting in any world
  disabledWorlds:
    - "disabled world"
    - "another disabled world"
  # Players are allowed to harvest crops with the items specified in this. Possible values are found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  # Adding "*", or by using '[]' would allow all items to be used
  requiredItems:
    - "WOODEN_HOE"
    - "STONE_HOE"
    - "GOLDEN_HOE"
    - "IRON_HOE"
    - "DIAMOND_HOE"
    - "NETHERITE_HOE"
  # True will check if the used tool has the specified enchantments, false will ignore this check
  requireEnchants: false
  # When true all enchants must be on the item to successfully replant the crop, when false only one enchant needs to be present on the item
  requireAllEnchants: false
  requiredEnchants:
    - "SILK_TOUCH"
  # When true the used item will lose durability
  useDurability: true
  # The name of the particle that spawns when a crop is replanted
  particle: "VILLAGER_HAPPY"
  # The amount of particles that spawn when a crop is replanted (use 0 to disable the spawn of particles)
  particleAmount: 10
  # The delay in ticks it takes to replant the crop
  delay: 15

CropTrampling:
  # Disables/enables the crop trampling system (a full server restart is needed to apply changes for this option)
  enabled: true
  # When true players need the permission epicreplant.trampling
  requirePermission: true
  # Use '[]' or '-' to allow replanting in any world
  disabledWorlds: []
  # Disables/enables the need of leather boots to make the antiCropTrampling work
  requireBoots: true
  # Mobs in this list are allowed to trample crops. Possible values are found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
  # Adding "*" to this list would allow all mobs to trample crops.
  blacklistedMobs:
    - "*"
